
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dscatterf.c lgcf.c histsf.c barsf.c axiscf.c lgf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscsys
LOCDIR    = src/sys/classes/draw/utils/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
