
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = daindexf.c dageometryf.c gr1f.c daf.c daddf.c dadistf.c fddaf.c dapreallocatef.c dagtonaf.c dacreatef.c dagetelemf.c dainterpf.c dagtolf.c dagetarrayf.c dasubf.c dalocalf.c dacornf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libpetscdm
LOCDIR   = src/dm/impls/da/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
