
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dualspacerefinedf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscdm
LOCDIR    = src/dm/dt/dualspace/impls/refined/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
