
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = plexrefregularf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscdm
LOCDIR    = src/dm/impls/plex/transform/impls/refine/regularftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
