
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = viewregf.c viewf.c flushf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscsys
LOCDIR    = src/sys/classes/viewer/interface/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
