
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = drawf.c dmarkerf.c dellipsef.c dsavef.c dclearf.c dcoorf.c drectf.c dtextf.c dpausef.c dflushf.c drawregf.c dviewpf.c dlinef.c dtrif.c dmousef.c dpointf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE   = libpetscsys
LOCDIR    = src/sys/classes/draw/interface/ftn-auto/
include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
